//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> idAddress { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> Money { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
