//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    
    public partial class spGetAllDonHang_Result1
    {
        public Nullable<long> C_No { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string InfoProduct { get; set; }
        public Nullable<double> TotalProductCost { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> FeeShip { get; set; }
        public Nullable<double> TotalPay { get; set; }
        public Nullable<double> Paid { get; set; }
    }
}
