//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string TomTat { get; set; }
        public string HinhAnh { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGianViet { get; set; }
        public string TacGia { get; set; }
        public string LinkSeo { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
